### ISSUE TITLE
Bonjour in Mac OS 9

### ISSUE THREAD

**Issue by VitaliyYakob** [dgsga/netatalk#2]
Hi.

I can't understand how it works, or it doesn't work yet?
In the Global section, I added "afpstats = yes"
I transfer "Multicast DNS & DNS-SD" and "Netatalk Server" to "System Folder:Extension", reboot Mac OS 9 -- Chooser does not find the server automatically.
I'm looking through traffic in WireShark, requests are coming. I checked with or without an extension, the requests are the same.

I also have an extension installed for Chooser MacNFS -- it finds an NFS server in its network segment.

Am I missing something in the server or client configuration, or is it not working yet?

P.S.
After my first message about a problem copying to a Netatalk server, the performance of the daemon fell.
Previously, the copy speed was ~200Mbps, and now only ~90Mbps.

**Comment by dgsga** [comment]
The Bonjour extension is just there in case you want your OS 9 Mac to show up in the Finder sidebar on other Macs that fully support both AFP and Bonjour (Mac OS X 10.4 to 10.8). It won't work with modern Macs. As for the copy speed it always varies hugely. I've done repeated transfers of the same file and there seems to be no logic as to whether it's a fast or slow copy. Copy speed also depends on file size. Remember Netatalk is a 20 year old piece of software!!

**Comment by VitaliyYakob** [comment]
I see, I misunderstood the purpose of this extension, and began to compare with MacNFS extension. :)
Thanks
