### ISSUE TITLE
followed instructions, on intel and m1 and same error: meson.build:32:2: ERROR: C shared or static library 'crypto' not found

### ISSUE THREAD

**Issue by krolingo** [dgsga/netatalk#3]
meson.build:32:2: ERROR: C shared or static library 'crypto' not found

what can I do to correct this?

**Comment by dgsga** [comment]
Have you definitely installed libressl with Homebrew? That's all you should need to do.
`brew install libressl`

**Comment by krolingo** [comment]
yes that did it, thank you.
