### ISSUE TITLE
ad->ad_ops->ad_mkrf(ad_p) failed: Operation not permitted │

### ISSUE THREAD

**Issue by krolingo** [dgsga/netatalk#4]
I did this:
Grant /usr/local/sbin/afpd and /usr/local/sbin/cnid_metad Full Disk Access in System Preferences (allows filesharing from APFS volumes)

But I'm getting these errors on any shares other than home:

│Feb 17 13:37:39.171082 afpd[58507] {ad_open.c:1112} (error:Default): ad->ad_ops->ad_mkrf(ad_p) failed: Operation not permitted               │
│Feb 17 13:37:44.424251 afpd[58507] {ad_open.c:1112} (error:Default): ad->ad_ops->ad_mkrf(ad_p) failed: Operation not permitted               │
│Feb 17 13:37:51.001472 afpd[58507] {ad_open.c:1112} (error:Default): ad->ad_ops->ad_mkrf(ad_p) failed: Operation not permitted

**Comment by krolingo** [comment]
I figured it out. 
You can only *reliably* share HFS+ volumes
* You need to give Full Disk Access to one of these  bash, sh, zsh (I don't know which one the system is using so I gave access to all of them)
* I also gave Full Disk Access to afpd, cnid_dbd, cnid_metad, netatalk, 
* but I believe all you need is:
1) System Shell (zsh on Monterey?) + 2) afpd and 3) cnid_metad

I will test further and report back. 

Thank you for creating this!

**Comment by dgsga** [comment]
Thanks for the feedback @krolingo. Please try again with latest commit [d6261bf](https://github.com/dgsga/netatalk/commit/d6261bf2acd2215912f39baae4ae9563b53eaffd) and let me know if this works for you. Fine over here _so far_...
