### ISSUE TITLE
Where is afp.conf file and how do I specify AFP shares as needed.

### ISSUE THREAD

**Issue by vaccinemedia** [dgsga/netatalk#6]
Where is this file?

**Comment by dgsga** [comment]
The afp.conf file is in /usr/local/etc. Please read the Netatalk online documentation:
https://netatalk.sourceforge.io/3.1/htmldocs/configuration.html#idm140604593213744

**Comment by vaccinemedia** [comment]
OK thanks for pointing me in the right direction :) I can now see my home directory on the networked mac. I can't however get to the UDB drive connected to it with name "Backup 10TB"

I have added:
[Backup 10TB]
path = "/Volumes/Backup 10TB"

But it's not working. Can you please give me some help and let me know where I am going wrong?

**Comment by krolingo** [comment]
> OK thanks for pointing me in the right direction :) I can now see my home directory on the networked mac. I can't however get to the USB drive connected to it with name "Backup 10TB"
> 
> I have added: [Backup 10TB] path = "/Volumes/Backup 10TB"
> 
> But it's not working. Can you please give me some help and let me know where I am going wrong?

remove the space, call it Backup_10TB, or Backup10TB, format it for HFS+ also
