### ISSUE TITLE
LDAP functionality for Apple Server App-created Open Directory DB not working

### ISSUE THREAD

**Issue by Hyperblue** [dgsga/netatalk#7]
Cannot get netatalk to connect to LDAP database that was created using Apple's "Server" App form the Apple App Store. MacOS Big Sur Intel MacPro

afpldaptest -g netshare
Start parsing afp.conf
Mar 18 16:04:37.160998 [22123] {iniparser.c:634} (error:Default): iniparser: cannot open "/usr/local/etcafp.conf"
Mar 18 16:04:37.161656 [22123] {ldap_config.c:93} (info:AFPDaemon): LDAP: not used
Finished parsing afp.conf
afp.conf is not ok, not using LDAP. Only local UUID testing available.
Searching group: netshare
Group: netshare ==> UUID: ABCDEFAB-CDEF-ABCD-EFAB-CDEF00000401

afp.conf file contents for LDAP (I have tried changing the below to other suggestions that showed up on Google to no avail:
ldap server = 127.0.0.1
ldap auth method = simple
ldap auth dn = admin
ldap auth pw = mypassword
ldap userbase = users
ldap userscope = one
ldap groupbase = groups
ldap groupscope = one
ldap uuid attr = apple-generateduid
ldap name attr = cn
ldap group attr = cn
ldap uuid string = XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
ldap uuid encoding = string

afpd -V 
afpd has been compiled with support for these features:

          AFP versions:	2.2 3.0 3.1 3.2 3.3 3.4 
         CNID backends:	dbd last tdb mysql 
      Zeroconf support:	mDNSResponder
   Admin group support:	Yes
    Valid shell checks:	Yes
            EA support:	ad | sys
           ACL support:	Yes
          LDAP support:	Yes
         D-Bus support:	Yes
     Spotlight support:	Yes

              afp.conf:	/usr/local/etc/afp.conf
           extmap.conf:	/usr/local/etc/extmap.conf
       state directory:	/usr/local/var/netatalk/
    afp_signature.conf:	/usr/local/var/netatalk/afp_signature.conf
      afp_voluuid.conf:	/usr/local/var/netatalk/afp_voluuid.conf
       UAM search path:	/usr/local/lib/netatalk/
  Server messages path:	/usr/local/var/netatalk/msg/

**Comment by dgsga** [comment]
Thanks for spotting this. Should be fixed in commit [1335755](https://github.com/dgsga/netatalk/commit/13357555e7dc5dfb5bbc54c9d009eac9e9adb075)
